// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	covidservice "covid-19-project/internal/covid/covidservice"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCovidService is a mock of CovidService interface.
type MockCovidService struct {
	ctrl     *gomock.Controller
	recorder *MockCovidServiceMockRecorder
}

// MockCovidServiceMockRecorder is the mock recorder for MockCovidService.
type MockCovidServiceMockRecorder struct {
	mock *MockCovidService
}

// NewMockCovidService creates a new mock instance.
func NewMockCovidService(ctrl *gomock.Controller) *MockCovidService {
	mock := &MockCovidService{ctrl: ctrl}
	mock.recorder = &MockCovidServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCovidService) EXPECT() *MockCovidServiceMockRecorder {
	return m.recorder
}

// GetCovidSummary mocks base method.
func (m *MockCovidService) GetCovidSummary() (*covidservice.CovidResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCovidSummary")
	ret0, _ := ret[0].(*covidservice.CovidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCovidSummary indicates an expected call of GetCovidSummary.
func (mr *MockCovidServiceMockRecorder) GetCovidSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCovidSummary", reflect.TypeOf((*MockCovidService)(nil).GetCovidSummary))
}
