// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package covid

import (
	"covid-19-project/internal/covid/covidclient"
	"covid-19-project/internal/covid/covidhandler"
	"covid-19-project/internal/covid/covidservice"
)

// Injectors from wire.go:

func Wire() (covidhandler.CovidHandler, error) {
	covidClientImp := covidclient.ProviderCovidClient()
	covidServiceImp := covidservice.ProviderCovidService(covidClientImp)
	covidHandlerImp := covidhandler.ProviderCovidHandler(covidServiceImp)
	return covidHandlerImp, nil
}
